# Conexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mafer_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

# Corregir WARN de OSIV
spring.jpa.open-in-view = false

server-port=8080

# Habilitar/deshabilitar (api-docs - swagger-ui)
# Estandar de documentacion open-api. Documentacion en api-docs (JSON) y la visualizacion en swagger-iu (Front)
springdoc.api-docs.enabled=true  
springdoc.swagger-ui.enabled=true

# Definir la ruta de swagger-iu
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Podemos seleccionar que paquetes y clases escanear (si no queremos escanear toda la api)
# Toda la api se encuentra en http://localhost:8080/doc/swagger-ui/index.html#/
#springdoc.packagesToScan=com.paquete1
#springdoc.pathsToMatch=/test/**, /support/**, /xyz/**, /gm.mafer/**

### Mas info en https://springdoc.org

# usar esta configuracion para acceder al login standard de spring security (sin personalizacion)
# acceso por 'localhost:8080/login' (sin .html)
# spring.security.user.name = mafer
# spring.security.user.password = password
# spring.security.user.roles=ADMIN

